import { Html, Head, Main, NextScript } from "next/document";
import { PageNavbar } from "./blocks/navbar.jsx";

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <link rel="icon" href="/images/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body>
        <PageNavbar />

        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
